config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :grades
  resources :subjects
  resources :students
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :student
  belongs_to :subject
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :grades
  def age
    ((Date.today - self.birth_date)/365).to_i
  end
  
  def to_s
    name + " " + surname
  end
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :grades
  def to_s
    name
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  # GET /grades
  # GET /grades.json
  def index
    @grades_grid = initialize_grid(Grade.all.joins(:student, :subject))
  end

  # GET /grades/1
  # GET /grades/1.json
  def show
  end

  # GET /grades/new
  def new
    @grade = Grade.new
  end

  # GET /grades/1/edit
  def edit
  end

  # POST /grades
  # POST /grades.json
  def create
    @grade = Grade.new(grade_params)

    respond_to do |format|
      if @grade.save
        format.html { redirect_to @grade, notice: 'Grade was successfully created.' }
        format.json { render :show, status: :created, location: @grade }
      else
        format.html { render :new }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /grades/1
  # PATCH/PUT /grades/1.json
  def update
    respond_to do |format|
      if @grade.update(grade_params)
        format.html { redirect_to @grade, notice: 'Grade was successfully updated.' }
        format.json { render :show, status: :ok, location: @grade }
      else
        format.html { render :edit }
        format.json { render json: @grade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /grades/1
  # DELETE /grades/1.json
  def destroy
    @grade.destroy
    respond_to do |format|
      format.html { redirect_to grades_url, notice: 'Grade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:value, :date, :student_id, :subject_id)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students_grid = initialize_grid(Student)
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @grades_grid = initialize_grid(@student.grades)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :surname, :birth_date)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subject_grid = initialize_grid(Subject)
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def style_active(path)
    return "active" if (request.path == path)
  end
  def menu_item(body, url)
    link = link_to body, url, class: ["nav-link",style_active(url)]
    content_tag :li, link, class: "nav-item"
  end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/grades/_form.html.erb
<%= form_with(model: grade, local: true) do |form| %>
  <% if grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value, id: :grade_value %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :grade_date %>
  </div>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.select :student_id, Student.all.collect{|s|[s.to_s, s.id]} %>
  </div>

  <div class="field">
    <%= form.label :subject_id %>
    <%= form.select :subject_id, Subject.all.collect{|s|[s.name, s.id]} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Show', @grade %> |
<%= link_to 'Back', grades_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grades</h1>

<%= grid(@grades_grid) do |g|

  g.column attribute: "value", name: "Hodnota"

  g.column attribute: "date", name: "Datum"

  g.column assoc: :student, attribute: "id", name: "Student" do |grade|
  	grade.student.to_s
  end
  
  g.column attribute: "name", assoc: :subject, name: "Predmet"

  g.column do |grade|
    link_to('Edit', edit_grade_path(grade))
  end
  g.column do |grade|
    link_to('Show', grade_path(grade))
  end
end -%>

<br>

<%= link_to 'Nova znamka', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form', grade: @grade %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @grade.value %>
</p>

<p>
  <strong>Date:</strong>
  <%= @grade.date %>
</p>

<p>
  <strong>Student:</strong>
  <%= @grade.student %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @grade.subject %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Menu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
    	<%
    	menu_definition = [{body: "Students", url: students_path},
    	 {body: "Subjects", url: subjects_path},
    	 {body: "Grades", url: grades_path}	
    	]
    	
    	menu_definition.each do |item|
    		concat menu_item item[:body], item[:url] 
    	end
    	%>
    	
    	
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentReports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  	<%= render 'layouts/menu' %>
    <%= yield %>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :student_surname %>
  </div>

  <div class="field">
    <%= form.label :birth_date %>
    <%= form.date_select :birth_date, id: :student_birth_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student_grades.html.erb
<%=

grid(@grades_grid) do |g|
	g.column attribute: "value", name: "Value"
	g.column attribute: "name", name: "Subject", assoc: :subject    
end

%>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<%= grid(@students_grid) do |g|

  g.column attribute: "id", name: "ID"

  g.column attribute: "name", name: "Jmeno"

  g.column attribute: "surname", name: "Prijmeni"

  g.column do |student|
    student.age
  end

  g.column do |task|
    link_to('Edit', edit_student_path(task))
  end
  g.column do |task|
    link_to('Show', student_path(task))
  end
end -%>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @student.surname %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @student.birth_date %>
</p>

<%= render 'student_grades', student: @student %>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<%= grid(@subject_grid) do |g|

  g.column attribute: "id", name: "ID"

  g.column attribute: "name", name: "Nazev"

  g.column do |subject|
    link_to('Edit', edit_subject_path(subject))
  end
  g.column do |subject|
    link_to('Show', subject_path(subject))
  end
end -%>
<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>